apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-origin-issuer-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '19'
spec:
  project: default
  source:
    repoURL: https://github.com/cloudflare/origin-ca-issuer
    path: deploy/crds
    targetRevision: v0.8.0
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true